name: Trigger Python Scripts

on:

  workflow_dispatch:

jobs:
  update-live-streams:
    runs-on: ubuntu-latest

    steps:
      - name: üì• Checkout repository
        uses: actions/checkout@v4

      - name: üêç Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: üì¶ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin google-cloud-firestore
          

      - name: üöÄ Run All Videos Fetch
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python All-Videos-Fetch.py


      - name: üõï Run Takht Sri Kesgarh Sahib Fetch
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python Takht-Sri-Kesgarh-Sahib-Fetch.py



     
